# Generated by Django 4.0.3 on 2022-07-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngdonator', models.CharField(max_length=20)),
                ('ngaddress', models.CharField(max_length=40)),
                ('ngcontact', models.IntegerField(max_length=11)),
                ('ngname', models.CharField(max_length=40)),
                ('ngplace', models.CharField(max_length=40)),
                ('ngdonation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportingParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rparty', models.CharField(max_length=30)),
                ('raddress', models.TextField()),
                ('rcontact', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='VictimsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(max_length=30)),
                ('vdate', models.TextField(default='', max_length=10)),
                ('vtime', models.TextField(max_length=5)),
                ('vname', models.CharField(max_length=30)),
                ('vaddress', models.TextField()),
                ('vcontact', models.IntegerField(max_length=11)),
                ('vdescription', models.TextField()),
                ('rpartyId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eknows.reportingparty')),
            ],
        ),
    ]
