# Generated by Django 4.0.3 on 2022-07-08 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eknows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportparty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eknows.reportingparty')),
                ('victims', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eknows.victimsinformation')),
            ],
        ),
    ]
